export enum AiModel {
  GPT_5_2 = 'gpt-5.2',
  // GPT_5_1 = 'gpt-5.1',
  GPT_5 = 'gpt-5',
  GPT_5_MINI = 'gpt-5-mini',
  GPT_4_1 = 'gpt-4.1',
  GPT_4_O = 'gpt-4o',
  // GPT_4_1_MINI = 'gpt-4.1-mini',
  TEXT_EMBEDDING_3_SMALL = 'text-embedding-3-small',
  CLAUDE_SONNET_4_5 = 'claude-sonnet-4-5',
  CLAUDE_HAIKU_4_5 = 'claude-haiku-4-5',
  CLAUDE_OPUS_4_5 = 'claude-opus-4-5',
}

export enum Theme {
  LIGHT = 'light',
  SILENT_PEAKS = 'silentPeaks',
  GOLDEN_HOUR = 'goldenHour',
  VINTAGE_PAPER = 'vintagePaper',
  ZEN_MIND = 'zenMind',
  BALANCE = 'balance',
  LEAF_SCAPE = 'leafScape',
  PASTEL_COLLAGE = 'pastelCollage',
  SEA_WHISPER = 'seaWhisper',
  WHITE_LOTUS = 'whiteLotus',
  PINK_WHISPER = 'pinkWhisper',
  PAPER_ROSE = 'paperRose',
  BLUE_BLOOM = 'blueBloom',
  SOFT_WAVES = 'softWaves',
  CALM_MIND = 'calmMind',
  ORANGE = 'orange',
  BALL = 'ball',
  COMPASS = 'compass',
  OCEAN_DEPTHS = 'oceanDepths',
  NEON_FOCUS = 'neonFocus',
  CIPHERED_NIGHT = 'cipheredNight',
  DREAM_ACHIEVE = 'dreamAchieve',
  TIME_TO_LIVE = 'timeToLive',
  DARK = 'dark',
}

export enum Font {
  ROBOTO = 'Roboto',
  OPEN_SANS = 'OpenSans',
  SF_PRO_DISPLAY = 'SFProDisplay',
  MONSERRAT = 'Montserrat',
  INTER = 'Inter',
  LATO = 'Lato',
  NUNITO = 'Nunito',
  SOURCE_CODE_PRO = 'SourceCodePro',
  FIRA_SANS = 'FiraSans',
  MANROPE = 'Manrope',
  TINOS = 'Tinos',
  UBUNTU = 'Ubuntu',
  EXO2 = 'Exo2',
  OSWALD = 'Oswald',
  RUBIK = 'Rubik',
}

export enum TimeFormat {
  '12_H' = '12h',
  '24_H' = '24h',
}

export enum DateFormat {
  DMY = 'dmy',
  MDY = 'mdy',
}

export enum Lang {
  EN = 'en',
  UK = 'uk',
}

export enum ConversationLanguage {
  ID = 'id',
  MS = 'ms',
  BS = 'bs',
  CA = 'ca',
  CS = 'cs',
  DA = 'da',
  DE = 'de',
  EN = 'en',
  ES = 'es',
  FR = 'fr',
  GL = 'gl',
  HR = 'hr',
  IT = 'it',
  HU = 'hu',
  NL = 'nl',
  NO = 'no',
  PL = 'pl',
  PT = 'pt',
  RO = 'ro',
  SK = 'sk',
  FI = 'fi',
  SV = 'sv',
  TL = 'tl',
  VI = 'vi',
  TR = 'tr',
  BG = 'bg',
  MK = 'mk',
  UK = 'uk',
  AR = 'ar',
  ZH = 'zh',
  EL = 'el',
  HI = 'hi',
  JA = 'ja',
  KO = 'ko',
  TA = 'ta',
  TH = 'th',
}
