import { ForumCategorySlug } from 'src/forum/types/forum-category-slug.enum';

export const FORUM_CATEGORY_SEED = [
  {
    slug: ForumCategorySlug.SELF_GROWTH,
    title: 'Self-growth',
    description: 'selfGrowthDescription',
    icon: 'sparkles',
    sortOrder: 10,
    isActive: true,
  },
  {
    slug: ForumCategorySlug.HABITS,
    title: 'Habits',
    description: 'habitsDescription',
    icon: 'repeat',
    sortOrder: 20,
    isActive: true,
  },
  {
    slug: ForumCategorySlug.GOALS,
    title: 'Goals',
    description: 'goalsDescription',
    icon: 'target',
    sortOrder: 30,
    isActive: true,
  },
  {
    slug: ForumCategorySlug.PRODUCTIVITY,
    title: 'Productivity',
    description: 'productivityDescription',
    icon: 'clock',
    sortOrder: 40,
    isActive: true,
  },
  {
    slug: ForumCategorySlug.MINDSET,
    title: 'Mindset',
    description: 'mindsetDescription',
    icon: 'brain',
    sortOrder: 50,
    isActive: true,
  },
  {
    slug: ForumCategorySlug.STRESS_BALANCE,
    title: 'Stress & Balance',
    description: 'stressBalanceDescription',
    icon: 'leaf',
    sortOrder: 60,
    isActive: true,
  },
  {
    slug: ForumCategorySlug.JOURNALING,
    title: 'Journaling',
    description: 'journalingDescription',
    icon: 'book-open',
    sortOrder: 70,
    isActive: true,
  },
  {
    slug: ForumCategorySlug.MOTIVATION,
    title: 'Motivation',
    description: 'motivationDescription',
    icon: 'flame',
    sortOrder: 80,
    isActive: true,
  },
  {
    slug: ForumCategorySlug.RELATIONSHIPS,
    title: 'Relationships',
    description: 'relationshipsDescription',
    icon: 'users',
    sortOrder: 90,
    isActive: true,
  },
];
